(function(g){var window=this;'use strict';var fKa=function(a,b){return g.Lb(a,b)},F4=function(a,b,c){a.l.set(b,c)},G4=function(a){F4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Sa()).toString(36));
return a},H4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.an(a.l,b,c)},gKa=function(a,b){var c=[];
g.aj(b,function(d){try{var e=g.Qn.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Pn(e)&&c.push(d)},a);
return c},hKa=function(a,b){b=gKa(a,b);
g.zb(b,function(c){g.Qn.prototype.remove.call(this,c)},a)},iKa=function(a){if(a.V){if(a.V.locationOverrideToken)return{locationOverrideToken:a.V.locationOverrideToken};
if(null!=a.V.latitudeE7&&null!=a.V.longitudeE7)return{latitudeE7:a.V.latitudeE7,longitudeE7:a.V.longitudeE7}}return null},jKa=function(a,b){g.fb(a,b)||a.push(b)},I4=function(a){var b=0,c;
for(c in a)b++;return b},kKa=function(a,b){b=b instanceof g.Bc?b:g.Ic(b,/^data:image\//i.test(b));
a.src=g.Cc(b)},lKa=function(a){try{return g.A.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},mKa=function(a){if(a.Ag&&"function"==typeof a.Ag)return a.Ag();
if("string"===typeof a)return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Ib(a)},nKa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||"string"===typeof a)g.zb(a,b,void 0);else{if(a.yh&&"function"==typeof a.yh)var c=a.yh();else if(a.Ag&&"function"==typeof a.Ag)c=void 0;else if(g.La(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Jb(a);d=mKa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},oKa=function(a,b,c,d){var e=new g.Pm(null,void 0);
a&&g.Qm(e,a);b&&g.Rm(e,b);c&&g.Sm(e,c);d&&(e.J=d);return e},J4=function(){},K4=function(a,b){g.Kq[a]=!0;
var c=g.Iq();c&&c.publish.apply(c,arguments);g.Kq[a]=!1},L4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Mm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",pKa(this,a.capabilities||""),qKa(this,a.experiments||""))},pKa=function(a,b){a.capabilities.clear();
g.Je(b.split(","),g.Pa(fKa,rKa)).forEach(function(c){a.capabilities.add(c)})},qKa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},M4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},N4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},sKa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},tKa=function(a){return new M4(a)},uKa=function(a){return Array.isArray(a)?g.Oc(a,tKa):[]},O4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},P4=function(a){return Array.isArray(a)?"["+g.Oc(a,O4).join(",")+"]":"null"},Q4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},vKa=function(a){return g.Oc(a,function(b){return{key:b.id,
name:b.name}})},R4=function(a,b){return g.bb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},S4=function(a,b){return g.bb(a,function(c){return N4(c,b)})},wKa=function(){var a=(0,g.Qu)();
a&&hKa(a,a.i.vk(!0))},T4=function(){var a=g.Tu("yt-remote-connected-devices")||[];
g.wb(a);return a},xKa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Oc(a,function(d,e){return 0==e?d:d.substring(c.length)})},yKa=function(a){g.Su("yt-remote-connected-devices",a,86400)},V4=function(){if(U4)return U4;
var a=g.Tu("yt-remote-device-id");a||(a=Q4(),g.Su("yt-remote-device-id",a,31536E3));for(var b=T4(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return U4=d},W4=function(){var a=T4(),b=V4();
g.fb(a,b);g.Wu()&&g.yb(a,b);a=xKa(a);if(g.gb(a))try{g.zo("remote_sid")}catch(c){}else try{g.xo("remote_sid",a.join(","),-1)}catch(c){}},zKa=function(){return g.Tu("yt-remote-session-browser-channel")},AKa=function(){return g.Tu("yt-remote-local-screens")||[]},BKa=function(){g.Su("yt-remote-lounge-token-expiration",!0,86400)},CKa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Oc(AKa(),function(d){return d.loungeToken}),c=g.Oc(a,function(d){return d.loungeToken});
g.hh(c,function(d){return!g.fb(b,d)})&&BKa();
g.Su("yt-remote-local-screens",a,31536E3)},DKa=function(a,b){g.Su("yt-remote-session-browser-channel",a);
g.Su("yt-remote-session-screen-id",b);a=T4();b=V4();g.fb(a,b)||a.push(b);yKa(a);W4()},X4=function(a){a||(g.Vu("yt-remote-session-screen-id"),g.Vu("yt-remote-session-video-id"));
W4();a=T4();g.kb(a,V4());yKa(a)},EKa=function(){if(!Y4){var a=g.$n();
a&&(Y4=new g.Kn(a))}},FKa=function(){EKa();
return Y4?!!Y4.get("yt-remote-use-staging-server"):!1},Z4=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},GKa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},HKa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},$4=function(a){a.length?IKa(a.shift(),function(){$4(a)}):a5()},JKa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},IKa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.id(d,g.hg(a));(document.head||document.documentElement).appendChild(d)},KKa=function(){var a=Z4(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},a5=function(){var a=HKa();
a&&a(!1,"No cast extension found")},b5=function(){if(LKa){var a=2,b=HKa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;IKa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",a5,c)}},MKa=function(){b5();
var a=KKa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");$4(a)},OKa=function(){b5();
var a=KKa();a.push.apply(a,g.la(NKa.map(JKa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");$4(a)},c5=function(a,b,c){g.F.call(this);
this.G=null!=c?(0,g.C)(a,c):a;this.Ef=b;this.C=(0,g.C)(this.LL,this);this.i=!1;this.l=0;this.u=this.yb=null;this.B=[]},d5=function(a,b,c){g.F.call(this);
this.B=null!=c?a.bind(c):a;this.Ef=b;this.u=null;this.i=!1;this.l=0;this.yb=null},e5=function(a){a.yb=g.Km(function(){a.yb=null;
a.i&&!a.l&&(a.i=!1,e5(a))},a.Ef);
var b=a.u;a.u=null;a.B.apply(null,b)},f5=function(a){if(g.A.JSON)try{return g.A.JSON.parse(a)}catch(b){}return lKa(a)},g5=function(){},h5=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.A.setTimeout(function(){a()},b)},j5=function(a){i5.dispatchEvent(new PKa(i5,a))},PKa=function(a,b){g.Gl.call(this,"statevent",a);
this.stat=b},k5=function(){},QKa=function(){},SKa=function(a){return(a=RKa(a))?new ActiveXObject(a):new XMLHttpRequest},RKa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},l5=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.U_(this);this.u=new g.Jm;this.u.setInterval(250)},UKa=function(a,b,c){a.Mq=1;
a.Dl=G4(b.clone());a.Lo=c;a.G=!0;TKa(a,null)},m5=function(a,b,c,d,e){a.Mq=1;
a.Dl=G4(b.clone());a.Lo=null;a.G=c;e&&(a.TI=!1);TKa(a,d)},TKa=function(a,b){a.Dq=Date.now();
n5(a);a.Hm=a.Dl.clone();H4(a.Hm,"t",a.J);a.fu=0;a.Ge=a.i.Ez(a.i.Jt()?b:null);0<a.Fy&&(a.Sw=new d5((0,g.C)(a.JJ,a,a.Ge),a.Fy));a.B.Pa(a.Ge,"readystatechange",a.ZR);b=a.Wm?g.Sb(a.Wm):{};a.Lo?(a.Ix="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Ge.send(a.Hm,a.Ix,a.Lo,b)):(a.Ix="GET",a.TI&&!g.ze&&(b.Connection="close"),a.Ge.send(a.Hm,a.Ix,null,b));a.i.Gi(1)},XKa=function(a,b,c){for(var d=!0;!a.En&&a.fu<c.length;){var e=VKa(a,c);
if(e==o5){4==b&&(a.yl=4,j5(15),d=!1);break}else if(e==WKa){a.yl=4;j5(16);d=!1;break}else p5(a,e)}4==b&&0==c.length&&(a.yl=1,j5(17),d=!1);a.Ri=a.Ri&&d;d||(q5(a),r5(a))},VKa=function(a,b){var c=a.fu,d=b.indexOf("\n",c);
if(-1==d)return o5;c=Number(b.substring(c,d));if(isNaN(c))return WKa;d+=1;if(d+c>b.length)return o5;b=b.substr(d,c);a.fu=d+c;return b},ZKa=function(a,b){a.Dq=Date.now();
n5(a);var c=b?window.location.hostname:"";a.Hm=a.Dl.clone();F4(a.Hm,"DOMAIN",c);F4(a.Hm,"t",a.J);try{a.Ui=new ActiveXObject("htmlfile")}catch(m){q5(a);a.yl=7;j5(22);r5(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in s5)f=s5[f];else if(f in YKa)f=s5[f]=YKa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
s5[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.ed(g.dc("b/12014412"),d+"</body></html>");a.Ui.open();a.Ui.write(g.ad(c));a.Ui.close();a.Ui.parentWindow.m=(0,g.C)(a.xR,a);a.Ui.parentWindow.d=(0,g.C)(a.gI,a,!0);a.Ui.parentWindow.rpcClose=(0,g.C)(a.gI,a,!1);c=a.Ui.createElement("DIV");a.Ui.parentWindow.document.body.appendChild(c);d=g.Hc(a.Hm.toString());d=g.pd(g.Cc(d));d=g.ed(g.dc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.fd(c,d);a.i.Gi(1)},n5=function(a){a.OC=Date.now()+
a.C;
$Ka(a,a.C)},$Ka=function(a,b){if(null!=a.Rq)throw Error("WatchDog timer not null");
a.Rq=h5((0,g.C)(a.FR,a),b)},t5=function(a){a.Rq&&(g.A.clearTimeout(a.Rq),a.Rq=null)},r5=function(a){a.i.OD()||a.En||a.i.Bu(a)},q5=function(a){t5(a);
g.Di(a.Sw);a.Sw=null;a.u.stop();g.OEa(a.B);if(a.Ge){var b=a.Ge;a.Ge=null;b.abort();b.dispose()}a.Ui&&(a.Ui=null)},p5=function(a,b){try{a.i.ZH(a,b),a.i.Gi(4)}catch(c){}},bLa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;aLa(a,b,function(h){h?c(!0):g.A.setTimeout(function(){bLa(a,b,c,d,f)},f)})}},aLa=function(a,b,c){var d=new Image;
d.onload=function(){try{u5(d),c(!0)}catch(e){}};
d.onerror=function(){try{u5(d),c(!1)}catch(e){}};
d.onabort=function(){try{u5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{u5(d),c(!1)}catch(e){}};
g.A.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
kKa(d,a)},u5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},v5=function(a){g.$l.call(this);
this.headers=new g.Mm;this.ra=a||null;this.B=!1;this.ma=this.i=null;this.Fa=this.V="";this.G=0;this.u="";this.C=this.Ca=this.L=this.xa=!1;this.J=0;this.X=null;this.Ma="";this.Y=this.Ea=!1},cLa=function(a){return g.xe&&g.ae(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},dLa=function(a){return"content-type"==a.toLowerCase()},fLa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.G=5;eLa(a);w5(a)},eLa=function(a){a.xa||(a.xa=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},hLa=function(a){if(a.B&&"undefined"!=typeof g.Y_)if(a.ma[1]&&4==x5(a)&&2==a.getStatus())y5(a,"Local request error detected and ignored");
else if(a.L&&4==x5(a))g.Km(a.WH,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){y5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.zd(1,String(a.V));if(!f&&g.A.self&&g.A.self.location){var h=g.A.self.location.protocol;f=h.substr(0,h.length-1)}e=!gLa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.G=6;try{var l=2<x5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";eLa(a)}}finally{w5(a)}}},w5=function(a,b){if(a.i){iLa(a);
var c=a.i,d=a.ma[0]?g.Ia:null;a.i=null;a.ma=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},iLa=function(a){a.i&&a.Y&&(a.i.ontimeout=null);
a.X&&(g.A.clearTimeout(a.X),a.X=null)},x5=function(a){return a.i?a.i.readyState:0},z5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},y5=function(a,b){return b+" ["+a.Fa+" "+a.V+" "+a.getStatus()+"]"},jLa=function(a){this.i=a;
this.l=new g5},kLa=function(a){var b=A5(a.i,a.Hr,"/mail/images/cleardot.gif");
G4(b);bLa(b.toString(),5E3,(0,g.C)(a.EM,a),3,2E3);a.Gi(1)},C5=function(a){var b=a.i.L;
if(null!=b)j5(5),b?(j5(11),B5(a.i,a,!1)):(j5(12),B5(a.i,a,!0));else if(a.Lg=new l5(a,void 0,void 0,void 0),a.Lg.Wm=a.Gy,b=a.i,b=A5(b,b.Jt()?a.wr:null,a.Hy),j5(5),!g.xe||g.be(10))H4(b,"TYPE","xmlhttp"),m5(a.Lg,b,!1,a.wr,!1);else{H4(b,"TYPE","html");var c=a.Lg;a=!!a.wr;c.Mq=3;c.Dl=G4(b.clone());ZKa(c,a)}},D5=function(a,b,c){this.eb=1;
this.i=[];this.u=[];this.B=new g5;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},lLa=function(a,b){this.i=a;
this.map=b;this.context=null},mLa=function(a,b,c,d){g.Gl.call(this,"timingevent",a);
this.size=b;this.Ct=d},nLa=function(a){g.Gl.call(this,"serverreachability",a)},qLa=function(a){oLa(a);
if(3==a.eb){var b=a.Us++,c=a.ev.clone();F4(c,"SID",a.l);F4(c,"RID",b);F4(c,"TYPE","terminate");E5(a,c);b=new l5(a,a.l,b,void 0);b.Mq=2;b.Dl=G4(c.clone());kKa(new Image,b.Dl.toString());b.Dq=Date.now();n5(b)}pLa(a)},rLa=function(a){a.aN(1,0);
a.ev=A5(a,null,a.Iy);F5(a)},oLa=function(a){a.Il&&(a.Il.abort(),a.Il=null);
a.Td&&(a.Td.cancel(),a.Td=null);a.xk&&(g.A.clearTimeout(a.xk),a.xk=null);G5(a);a.yg&&(a.yg.cancel(),a.yg=null);a.Ql&&(g.A.clearTimeout(a.Ql),a.Ql=null)},sLa=function(a,b){if(0==a.eb)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new lLa(a.zO++,b));2!=a.eb&&3!=a.eb||F5(a)},tLa=function(a){var b=0;
a.Td&&b++;a.yg&&b++;return b},F5=function(a){a.yg||a.Ql||(a.Ql=h5((0,g.C)(a.eI,a),0),a.Up=0)},vLa=function(a,b){if(1==a.eb){if(!b){a.Us=Math.floor(1E5*Math.random());
b=a.Us++;var c=new l5(a,"",b,void 0);c.Wm=a.pj;var d=H5(a),e=a.ev.clone();F4(e,"RID",b);F4(e,"CVER","1");E5(a,e);UKa(c,e,d);a.yg=c;a.eb=2}}else 3==a.eb&&(b?uLa(a,b):0==a.i.length||a.yg||uLa(a))},uLa=function(a,b){if(b)if(6<a.Fn){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.Us-1;b=H5(a)}else c=b.L,b=b.Lo;else c=a.Us++,b=H5(a);var d=a.ev.clone();F4(d,"SID",a.l);F4(d,"RID",c);F4(d,"AID",a.nq);E5(a,d);c=new l5(a,a.l,c,a.Up+1);c.Wm=a.pj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yg=c;UKa(c,d,b)},E5=function(a,b){a.xf&&(a=a.xf.KF())&&g.Bb(a,function(c,d){F4(b,d,c)})},H5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Fn&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={kp:e.kp},f++){e.kp=a.i[f].i;var h=a.i[f].map;e.kp=6>=a.Fn?f:e.kp-d;try{g.Bb(h,function(l){return function(m,n){c.push("req"+l.kp+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.kp+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},wLa=function(a){a.Td||a.xk||(a.G=1,a.xk=h5((0,g.C)(a.dI,a),0),a.Jp=0)},I5=function(a){if(a.Td||a.xk||3<=a.Jp)return!1;
a.G++;a.xk=h5((0,g.C)(a.dI,a),xLa(a,a.Jp));a.Jp++;return!0},B5=function(a,b,c){a.Gx=c;
a.qj=b.gk;a.C||rLa(a)},G5=function(a){null!=a.Mn&&(g.A.clearTimeout(a.Mn),a.Mn=null)},xLa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},J5=function(a,b){if(2==b||9==b){var c=null;
a.xf&&(c=null);var d=(0,g.C)(a.CS,a);c||(c=new g.Pm("//www.google.com/images/cleardot.gif"),G4(c));aLa(c.toString(),1E4,d)}else j5(2);yLa(a,b)},yLa=function(a,b){a.eb=0;
a.xf&&a.xf.bF(b);pLa(a);oLa(a)},pLa=function(a){a.eb=0;
a.qj=-1;if(a.xf)if(0==a.u.length&&0==a.i.length)a.xf.oz();else{g.ob(a.u);var b=g.ob(a.i);a.u.length=0;a.i.length=0;a.xf.oz(b)}},A5=function(a,b,c){var d=g.Xm(c);
if(""!=d.i)b&&g.Rm(d,b+"."+d.i),g.Sm(d,d.u);else{var e=window.location;d=oKa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Wr&&g.Bb(a.Wr,function(f,h){F4(d,h,f)});
F4(d,"VER",a.Fn);E5(a,d);return d},zLa=function(){},ALa=function(){this.i=[];
this.l=[]},BLa=function(a,b){this.action=a;
this.params=b||{}},K5=function(a,b){g.F.call(this);
this.i=new g.J(this.pR,0,this);g.H(this,this.i);this.Ef=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.C)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.C)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},L5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ma=a;this.G=b;this.u=new g.Jn;this.l=new K5(this.jS,this);this.i=null;this.X=!1;this.C=null;this.V="";this.L=this.B=0;this.J=[];this.ra=c;this.Y=d;this.xa=e},CLa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Gx,sessionId:a.i.l,arrayId:a.i.nq}},DLa=function(a,b){a.L=b||0;
a.l.stop();M5(a);a.i&&(3==a.i.getState()&&vLa(a.i),qLa(a.i));a.L=0},N5=function(a){return!!a.i&&3==a.i.getState()},M5=function(a){if(a.i){var b=a.Y(),c=a.i.pj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.pj=c}},O5=function(a){this.port=this.domain="";
this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.zd(4,a))||"";b&&(this.port=":"+b);this.domain=g.Ad(a)||"";a=g.Uc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.zc(a,"10.0")&&(this.l=!1))},P5=function(a,b){var c=a.i;
a.l&&(c="https://"+a.domain+a.port+a.i);return g.Nd(c+b,{})},Q5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Pa(a.B,d,!0),onError:g.Pa(a.u,e),onTimeout:g.Pa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.op(b,a)},HLa=function(){var a=ELa;
FLa();R5.push(a);GLa()},S5=function(a,b){FLa();
var c=ILa(a,String(b));g.gb(R5)?JLa(c):(GLa(),g.zb(R5,function(d){d(c)}))},FLa=function(){R5||(R5=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",R5,void 0))},JLa=function(a){var b=(T5+1)%50;
T5=b;U5[b]=a;V5||(V5=49==b)},GLa=function(){var a=R5;
if(U5[0]){var b=V5?T5:-1;do{b=(b+1)%50;var c=U5[b];g.zb(a,function(d){d(c)})}while(b!=T5);
U5=Array(50);T5=-1;V5=!1}},ILa=function(a,b){var c=(Date.now()-KLa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},W5=function(a){g.O.call(this);
this.G=a;this.screens=[]},LLa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},MLa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Je(a.screens,function(f){return!!R4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=LLa(a,b[d])||c;return c},NLa=function(a,b){var c=a.screens.length;
a.screens=g.Je(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},X5=function(a,b,c,d,e){g.O.call(this);
this.u=a;this.J=b;this.B=c;this.G=d;this.C=e;this.l=0;this.i=null;this.yb=NaN},Z5=function(a){W5.call(this,"LocalScreenService");
this.l=a;this.i=NaN;Y5(this);this.info("Initializing with "+P4(this.screens))},OLa=function(a){if(a.screens.length){var b=g.Oc(a.screens,function(d){return d.id}),c=P5(a.l,"/pairing/get_lounge_token_batch");
Q5(a.l,c,{screen_ids:b.join(",")},(0,g.C)(a.xN,a),(0,g.C)(a.wN,a))}},Y5=function(a){if(g.Io("deprecate_pair_servlet_enabled"))return MLa(a,[]);
var b=uKa(AKa());b=g.Je(b,function(c){return!c.uuid});
return MLa(a,b)},$5=function(a,b){CKa(g.Oc(a.screens,sKa));
b&&BKa()},b6=function(a,b){g.O.call(this);
this.G=b;b=(b=g.Tu("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.G(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.fb(b,h)}this.i=c;this.C=a;this.u=this.B=NaN;this.l=null;a6("Initialized with "+g.Hj(this.i))},c6=function(a,b,c){var d=P5(a.C,"/pairing/get_screen_availability");
Q5(a.C,d,{lounge_token:b.token},(0,g.C)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.C)(function(){c(!1)},a))},d6=function(a,b){a:if(I4(b)!=I4(a.i))var c=!1;
else{c=g.Jb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(a6("Updated online screens: "+g.Hj(a.i)),a.i=b,a.W("screenChange"));PLa(a)},e6=function(a){isNaN(a.u)||g.jp(a.u);
a.u=g.hp((0,g.C)(a.NB,a),0<a.B&&a.B<g.Sa()?2E4:1E4)},a6=function(a){S5("OnlineScreenService",a)},QLa=function(a){var b={};
g.zb(a.G(),function(c){c.token?b[c.token]=c.id:this.Gd("Requesting availability of screen w/o lounge token.")});
return b},PLa=function(a){a=g.Jb(g.Cb(a.i,function(b){return b}));
g.wb(a);a.length?g.Su("yt-remote-online-screen-ids",a.join(","),60):g.Vu("yt-remote-online-screen-ids")},f6=function(a,b){b=void 0===b?!1:b;
W5.call(this,"ScreenService");this.B=a;this.J=b;this.i=this.l=null;this.u=[];this.C={};RLa(this)},TLa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Vg(),l=c?S4(h,c):null;c&&(a.J||l)||(l=S4(h,b));if(l){l.uuid=b;var m=g6(a,l);c6(a.i,m,function(n){e(n?m:null)})}else c?SLa(a,c,(0,g.C)(function(n){var p=g6(this,new M4({name:d,
screenId:c,loungeToken:n,dialId:b||""}));c6(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},ULa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},VLa=function(a,b,c){c6(a.i,b,c)},SLa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.op(P5(a.B,"/pairing/get_lounge_token_batch"),e)},WLa=function(a){a.screens=a.l.Vg();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+P4(a.screens))},RLa=function(a){h6(a);
a.l=new Z5(a.B);a.l.subscribe("screenChange",(0,g.C)(a.DN,a));WLa(a);a.J||(a.u=uKa(g.Tu("yt-remote-automatic-screen-cache")||[]));h6(a);a.info("Initializing automatic screens: "+P4(a.u));a.i=new b6(a.B,(0,g.C)(a.Vg,a,!0));a.i.subscribe("screenChange",(0,g.C)(function(){this.W("onlineScreenChange")},a))},g6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=S4(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),a.J||XLa(a));h6(a);a.C[b.uuid]=b.id;g.Su("yt-remote-device-id-map",a.C,31536E3);return b},XLa=function(a){a=g.Je(a.u,function(b){return"shortLived"!=b.idType});
g.Su("yt-remote-automatic-screen-cache",g.Oc(a,sKa))},h6=function(a){a.C=g.Tu("yt-remote-device-id-map")||{}},i6=function(a,b,c){g.O.call(this);
this.xa=c;this.u=a;this.i=b;this.B=null},j6=function(a,b){a.B=b;
a.W("sessionScreen",a.B)},YLa=function(a,b){a.B&&(a.B.token=b,g6(a.u,a.B));
a.W("sessionScreen",a.B)},k6=function(a,b){S5(a.xa,b)},l6=function(a,b,c){i6.call(this,a,b,"CastSession");
var d=this;this.Ca=c;this.l=null;this.Y=(0,g.C)(this.QL,this);this.ra=(0,g.C)(this.JR,this);this.X=g.hp(function(){ZLa(d,null)},12E4);
this.J=this.C=this.G=this.L=0;this.ma=!1;this.V="unknown"},m6=function(a,b){g.jp(a.J);
a.J=0;0==b?$La(a):a.J=g.hp(function(){$La(a)},b)},$La=function(a){aMa(a,"getLoungeToken");
g.jp(a.C);a.C=g.hp(function(){bMa(a,null)},3E4)},aMa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Hj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.C)(function(){k6(this,"Failed to send message: "+b+".")},a)):k6(a,"Sending yt message without session: "+g.Hj(c))},n6=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.ZF(b,function(c){j6(a,c)},function(){return a.Zf()},5)):a.Zf(Error("Waiting for session status timed out."))},dMa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new M4(b);cMa(a,d,function(e){e?(a.ma=!0,g6(a.u,d),j6(a,d),a.V="unknown",m6(a,c)):(g.No(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.Zf())},5)},ZLa=function(a,b){g.jp(a.X);
a.X=0;b?a.Ca.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?dMa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.No(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),n6(a,b.screenId))):(g.No(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),
n6(a,b.screenId)):n6(a,b.screenId):a.Zf(Error("Waiting for session status timed out."))},bMa=function(a,b){g.jp(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.V=c,m6(a,3E4)):(YLa(a,b.loungeToken),a.ma=!1,a.V="unknown",m6(a,b.loungeTokenRefreshIntervalMs))},cMa=function(a,b,c,d){g.jp(a.G);
a.G=0;VLa(a.u,b,function(e){e||0>d?c(e):a.G=g.hp(function(){cMa(a,b,c,d-1)},300)})},eMa=function(a){g.jp(a.L);
a.L=0;g.jp(a.G);a.G=0;g.jp(a.X);a.X=0;g.jp(a.C);a.C=0;g.jp(a.J);a.J=0},o6=function(a,b,c,d){i6.call(this,a,b,"DialSession");
this.Ea=d;this.l=this.L=null;this.ra="";this.Fa=c;this.Ba=null;this.X=g.Ia;this.V=NaN;this.Ca=(0,g.C)(this.RL,this);this.C=g.Ia;this.J=this.G=0;this.Y=!1;this.ma="unknown"},p6=function(a){var b;
return!!(a.Ea.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},fMa=function(a){a.C=a.u.QD(a.ra,a.i.label,a.i.friendlyName,p6(a),function(b,c){a.C=g.Ia;
a.Y=!0;j6(a,b);"shortLived"==b.idType&&0<c&&q6(a,c)},function(b){a.C=g.Ia;
a.Zf(b)})},gMa=function(a){var b={};
b.pairingCode=a.ra;b.theme=a.Fa;FKa()&&(b.env_useStageMdx=1);return g.Jd(b)},r6=function(a){return new Promise(function(b){a.ra=Q4();
if(a.Ba){var c=new chrome.cast.DialLaunchResponse(!0,gMa(a));b(c);fMa(a)}else a.X=function(){g.jp(a.V);a.X=function(){};
a.V=NaN;var d=new chrome.cast.DialLaunchResponse(!0,gMa(a));b(d);fMa(a)},a.V=g.hp(function(){a.X()},100)})},iMa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new M4(b);return(new Promise(function(e){hMa(a,d,function(f){f?(a.Y=!0,g6(a.u,d),j6(a,d),q6(a,c)):g.No(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):r6(a)})},jMa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){TLa(a.u,c,b,d,function(f){f&&f.token&&j6(a,f);e(f)},function(f){k6(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):r6(a)})},hMa=function(a,b,c,d){g.jp(a.G);
a.G=0;VLa(a.u,b,function(e){e||0>d?c(e):a.G=g.hp(function(){hMa(a,b,c,d-1)},300)})},q6=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
p6(a)&&(g.jp(a.J),a.J=0,0==b?kMa(a):a.J=g.hp(function(){kMa(a)},b))},kMa=function(a){p6(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ma=c,q6(a,3E4)):(a.Y=!1,a.ma="unknown",YLa(a,b.loungeToken),q6(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ma="noLoungeTokenResponse";q6(a,3E4)})},lMa=function(a){g.jp(a.G);
a.G=0;g.jp(a.J);a.J=0;a.C();a.C=function(){};
g.jp(a.V)},s6=function(a,b){i6.call(this,a,b,"ManualSession");
this.l=g.hp((0,g.C)(this.oq,this,null),150)},t6=function(a,b){g.O.call(this);
this.B=b;this.l=a;this.L=b.appId||"233637DE";this.C=b.theme||"cl";this.V=b.disableCastApi||!1;this.i=null;this.J=!1;this.u=[];this.G=(0,g.C)(this.FQ,this)},mMa=function(a,b){return b?g.bb(a.u,function(c){return N4(b,c.label)},a):null},u6=function(a){S5("Controller",a)},ELa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},v6=function(a){return a.J||!!a.u.length||!!a.i},w6=function(a,b,c){b!=a.i&&(g.Di(a.i),(a.i=b)?(c?a.W("yt-remote-cast2-receiver-resumed",
b.i):a.W("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.C)(a.cI,a,b)),b.getScreen()?a.W("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.oq(null)):a.W("yt-remote-cast2-session-change",null))},nMa=function(a){var b=a.l.PD(),c=a.i&&a.i.i;
a=g.Oc(b,function(d){c&&N4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=mMa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},sMa=function(a,b,c,d){d.disableCastApi?x6("Cannot initialize because disabled by Mdx config."):oMa()?pMa(b,d)&&(y6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?qMa(a,c):(window.__onGCastApiAvailable=function(e,f){e?qMa(a,c):(z6("Failed to load cast API: "+f),A6(!1),y6(!1),g.Vu("yt-remote-cast-available"),g.Vu("yt-remote-cast-receiver"),
rMa(),c(!1))},d.loadCastApiSetupScript?g.Xu("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=Z4()&&MKa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?a5():89<=Z4()?OKa():(b5(),$4(NKa.map(JKa))))):x6("Cannot initialize because not running Chrome")},rMa=function(){x6("dispose");
var a=B6();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);tMa(!1);g.Nq(C6);C6.length=0},D6=function(){return!!g.Tu("yt-remote-cast-installed")},uMa=function(){var a=g.Tu("yt-remote-cast-receiver");
return a?a.friendlyName:null},vMa=function(){x6("clearCurrentReceiver");
g.Vu("yt-remote-cast-receiver")},wMa=function(){return D6()?B6()?B6().getCastSession():(z6("getCastSelector: Cast is not initialized."),null):(z6("getCastSelector: Cast API is not installed!"),null)},F6=function(){D6()?B6()?E6()?(x6("Requesting cast selector."),B6().requestSession()):(x6("Wait for cast API to be ready to request the session."),C6.push(g.Mq("yt-remote-cast2-api-ready",F6))):z6("requestCastSelector: Cast is not initialized."):z6("requestCastSelector: Cast API is not installed!")},G6=
function(a,b){E6()?B6().setConnectedScreenStatus(a,b):z6("setConnectedScreenStatus called before ready.")},oMa=function(){var a=0<=g.Uc.search(/ (CrMo|Chrome|CriOS)\//);
return g.TA||a},xMa=function(a,b){B6().init(a,b)},pMa=function(a,b){var c=!1;
B6()||(a=new t6(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Su("yt-remote-cast-available",d);K4("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){x6("onReceiverSelected: "+d.friendlyName);
g.Su("yt-remote-cast-receiver",d);K4("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){x6("onReceiverResumed: "+d.friendlyName);
g.Su("yt-remote-cast-receiver",d);K4("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){x6("onSessionChange: "+O4(d));
d||g.Vu("yt-remote-cast-receiver");K4("yt-remote-cast2-session-change",d)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
x6("cloudview.createSingleton_: "+c);return c},B6=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},qMa=function(a,b){A6(!0);
y6(!1);xMa(a,function(c){c?(tMa(!0),g.Oq("yt-remote-cast2-api-ready")):(z6("Failed to initialize cast API."),A6(!1),g.Vu("yt-remote-cast-available"),g.Vu("yt-remote-cast-receiver"),rMa());b(c)})},x6=function(a){S5("cloudview",a)},z6=function(a){S5("cloudview",a)},A6=function(a){x6("setCastInstalled_ "+a);
g.Su("yt-remote-cast-installed",a)},E6=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},tMa=function(a){x6("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},y6=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},H6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.G=this.J=0;this.trackData=null;this.hasNext=this.Fj=!1;this.L=this.C=this.i=this.B=0;this.u=NaN;this.l=!1;this.reset(a)},I6=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Fj=!1;a.hasNext=!1;a.J=0;a.G=g.Sa();a.B=0;a.i=0;a.C=0;a.L=0;a.u=NaN;a.l=!1},J6=function(a){return a.lc()?(g.Sa()-a.G)/1E3:0},K6=function(a,b){a.J=b;
a.G=g.Sa()},L6=function(a){switch(a.playerState){case 1:case 1081:return(g.Sa()-a.G)/1E3+a.J;
case -1E3:return 0}return a.J},M6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&I6(a)},N6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Tb(a.trackData);b.hasPrevious=a.Fj;b.hasNext=a.hasNext;b.playerTime=a.J;b.playerTimeAt=a.G;b.seekableStart=a.B;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.L;b.liveIngestionTime=a.u;return b},P6=function(a,b){g.O.call(this);
this.eb=0;this.u=a;this.C=[];this.B=new ALa;this.l=this.i=null;this.L=(0,g.C)(this.hP,this);this.G=(0,g.C)(this.Xs,this);this.J=(0,g.C)(this.gP,this);this.V=(0,g.C)(this.oP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ZB,this),yMa(this))):c=3;0!=c&&(b?this.ZB(c):g.hp((0,g.C)(function(){this.ZB(c)},this),0));
(a=wMa())&&O6(this,a);this.subscribe("yt-remote-cast2-session-change",this.V)},Q6=function(a){return new H6(a.u.getPlayerContextData())},yMa=function(a){g.zb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Pa(this.CQ,b),this))},a)},zMa=function(a){g.zb(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},R6=function(a){return 1==a.getState()},S6=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},U6=function(a,b,c){var d=Q6(a);
K6(d,c);-1E3!=d.playerState&&(d.playerState=b);T6(a,d)},V6=function(a,b,c){a.u.sendMessage(b,c)},T6=function(a,b){zMa(a);
a.u.setPlayerContextData(N6(b));yMa(a)},O6=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.G),a.Xs(null));
a.l=b;a.l&&(S5("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.G),a.l.media.length&&a.Xs(a.l.media[0]))},AMa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=Q6(a);b.contentId!=d.videoId&&S5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;K6(d,a.i.getEstimatedTime());T6(a,d)}else S5("CP","No cast media video. Ignoring state update.")},W6=function(a,b,c){return(0,g.C)(function(d){this.Gd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Gd("Retrying "+b+" using MDx browser channel."),V6(this,b,c))},a)},X6=function(a,b,c){g.O.call(this);
this.C=NaN;this.ma=!1;this.L=this.J=this.X=this.Y=NaN;this.V=[];this.B=this.G=this.u=this.Zb=this.i=null;this.xa=a;this.V.push(g.Np(window,"beforeunload",(0,g.C)(this.tN,this)));this.l=[];this.Zb=new H6;this.Ca=b.id;this.ra=b.idType;this.i=BMa(this,c);this.i.subscribe("handlerOpened",this.lP,this);this.i.subscribe("handlerClosed",this.iP,this);this.i.subscribe("handlerError",this.jP,this);this.i.subscribe("handlerMessage",this.kP,this);this.i.hx(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.Zb.videoId;g.Wu()&&g.Su("yt-remote-session-video-id",d)},this)},Y6=function(a){S5("conn",a)},BMa=function(a,b){return new L5(P5(a.xa,"/bc"),b,!1,function(){return a.UD()},"shortLived"==a.ra)},Z6=function(a,b){a.W("proxyStateChange",b)},CMa=function(a){a.C=g.hp((0,g.C)(function(){Y6("Connecting timeout");
this.Qp(1)},a),2E4)},$6=function(a){g.jp(a.C);
a.C=NaN},a7=function(a){g.jp(a.Y);
a.Y=NaN},DMa=function(a){b7(a);
a.X=g.hp((0,g.C)(function(){c7(this,"getNowPlaying")},a),2E4)},b7=function(a){g.jp(a.X);
a.X=NaN},FMa=function(a,b){b&&($6(a),a7(a));
var c=N5(a.i)&&isNaN(a.C);b==c?b&&(Z6(a,1),c7(a,"getSubtitlesTrack")):b?(a.YF()&&a.Zb.reset(),Z6(a,1),c7(a,"getNowPlaying"),EMa(a)):a.Qp(1)},GMa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Zb.videoId&&(g.Ob(b.params)?a.Zb.trackData=null:a.Zb.trackData=b.params,a.W("remotePlayerChange"))},HMa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Zb.listId=b.params.listId||a.Zb.listId;M6(a.Zb,c,d);a.W("remoteQueueChange")},JMa=function(a,b){b.params=b.params||{};
HMa(a,b);IMa(a,b);a.W("autoplayDismissed")},IMa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
K6(a.Zb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Zb.playerState&&(c=-1E3);a.Zb.playerState=c;c=Number(b.params.loadedTime);a.Zb.L=isNaN(c)?0:c;c=Number(b.params.duration);a.Zb.C=isNaN(c)?0:c;c=a.Zb;var d=Number(b.params.liveIngestionTime);c.u=d;c.l=isNaN(d)?!1:!0;c=a.Zb;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.Zb.playerState?DMa(a):b7(a);a.W("remotePlayerChange")},KMa=function(a,b){if(-1E3!=a.Zb.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Zb.playerState=c;b=parseInt(b.params.currentTime,10);K6(a.Zb,isNaN(b)?0:b);a.W("remotePlayerChange")}},LMa=function(a,b){var c="true"==b.params.muted;
a.Zb.volume=parseInt(b.params.volume,10);a.Zb.muted=c;a.W("remotePlayerChange")},MMa=function(a,b){a.G=b.params.videoId;
a.W("nowAutoplaying",parseInt(b.params.timeout,10))},NMa=function(a,b){var c="true"==b.params.hasNext;
a.Zb.Fj="true"==b.params.hasPrevious;a.Zb.hasNext=c;a.W("previousNextChange")},EMa=function(a){g.jp(a.L);
a.L=g.hp((0,g.C)(a.Qp,a,1),864E5)},c7=function(a,b,c){c?Y6("Sending: action="+b+", params="+g.Hj(c)):Y6("Sending: action="+b);
a.i.sendMessage(b,c)},d7=function(a){W5.call(this,"ScreenServiceProxy");
this.Df=a;this.i=[];this.i.push(this.Df.$_s("screenChange",(0,g.C)(this.VL,this)));this.i.push(this.Df.$_s("onlineScreenChange",(0,g.C)(this.jQ,this)))},RMa=function(a,b){EKa();
if(!Y4||!Y4.get("yt-remote-disable-remote-module-for-dev")){b=g.M("MDX_CONFIG")||b;wKa();W4();e7||(e7=new O5(b?b.loungeApiHost:void 0),FKa()&&(e7.i="/api/loungedev"));f7||(f7=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",f7,void 0));OMa();var c=g7();if(!c){var d=new f6(e7,b?b.disableAutomaticScreenCache||!1:!1);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=g7();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});sMa(a,d,function(f){f?h7()&&G6(h7(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){K4("yt-remote-receiver-availability-change")})},e)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),i7("Initializing: "+g.Hj(b)),j7.push(g.Mq("yt-remote-cast2-availability-change",function(){K4("yt-remote-receiver-availability-change")})),j7.push(g.Mq("yt-remote-cast2-receiver-selected",
function(){k7(null);
K4("yt-remote-auto-connect","cast-selector-receiver")})),j7.push(g.Mq("yt-remote-cast2-receiver-resumed",function(){K4("yt-remote-receiver-resumed","cast-selector-receiver")})),j7.push(g.Mq("yt-remote-cast2-session-change",PMa)),j7.push(g.Mq("yt-remote-connection-change",function(f){f?G6(h7(),"YouTube TV"):l7()||(G6(null,null),vMa())})),a=m7(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.Io("desktop_enable_autoplay")&&e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=
b.theme)&&(a.theme=b),i7(" -- with channel params: "+g.Hj(a)),a?(g.Su("yt-remote-session-app",a.app),g.Su("yt-remote-session-name",a.name)):(g.Vu("yt-remote-session-app"),g.Vu("yt-remote-session-name")),g.Ga("yt.mdx.remote.channelParams_",a,void 0),c.start(),h7()||QMa())}},SMa=function(){var a=g7().Df.$_gos();
var b=n7();b&&o7()&&(R4(a,b)||a.push(b));return vKa(a)},p7=function(){var a=TMa();
!a&&D6()&&uMa()&&(a={key:"cast-selector-receiver",name:uMa()});return a},TMa=function(){var a=SMa(),b=n7();
b||(b=l7());return g.bb(a,function(c){return b&&N4(b,c.key)?!0:!1})},n7=function(){var a=h7();
if(!a)return null;var b=g7().Vg();return S4(b,a)},PMa=function(a){i7("remote.onCastSessionChange_: "+O4(a));
if(a){var b=n7();if(b&&b.id==a.id){if(G6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))q7&&(q7.token=a),(b=o7())&&b.hx(a)}else b&&r7(),s7(a,1)}else o7()&&r7()},r7=function(){E6()?B6().stopSession():z6("stopSession called before API ready.");
var a=o7();a&&(a.disconnect(1),t7(null))},u7=function(){var a=o7();
return!!a&&3!=a.getProxyState()},i7=function(a){S5("remote",a)},g7=function(){if(!v7){var a=g.Ha("yt.mdx.remote.screenService_");
v7=a?new d7(a):null}return v7},h7=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},UMa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},VMa=function(){return g.Ha("yt.mdx.remote.connectData_")},k7=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},o7=function(){return g.Ha("yt.mdx.remote.connection_")},t7=function(a){var b=o7();
k7(null);a||UMa("");g.Ga("yt.mdx.remote.connection_",a,void 0);f7&&(g.zb(f7,function(c){c(a)}),f7.length=0);
b&&!a?K4("yt-remote-connection-change",!1):!b&&a&&K4("yt-remote-connection-change",!0)},l7=function(){var a=g.Wu();
if(!a)return null;var b=g7();if(!b)return null;b=b.Vg();return S4(b,a)},s7=function(a,b){h7();
n7()&&n7();w7?q7=a:(UMa(a.id),a=new X6(e7,a,m7()),a.connect(b,VMa()),a.subscribe("beforeDisconnect",function(c){K4("yt-remote-before-disconnect",c)}),a.subscribe("beforeDispose",function(){o7()&&(o7(),t7(null))}),a.subscribe("browserChannelAuthError",function(){var c=n7();
c&&"shortLived"==c.idType&&(E6()?B6().handleBrowserChannelAuthError():z6("refreshLoungeToken called before API ready."))}),t7(a))},QMa=function(){var a=l7();
a?(i7("Resume connection to: "+O4(a)),s7(a,0)):(X4(),vMa(),i7("Skipping connecting because no session screen found."))},OMa=function(){var a=m7();
if(g.Ob(a)){a=V4();var b=g.Tu("yt-remote-session-name")||"",c=g.Tu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},m7=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},x7=function(a,b,c){g.F.call(this);
var d=this;this.l=a;this.I=b;this.Ob=c;this.events=new g.YL(this);this.X=this.events.N(this.I,"onVolumeChange",function(e){WMa(d,e)});
this.C=!1;this.suggestion=null;this.G=new g.aJ(64);this.i=new g.J(this.bJ,500,this);this.u=new g.J(this.cJ,1E3,this);this.L=new c5(this.US,0,this);this.B={};this.V=new g.J(this.CJ,1E3,this);this.J=new d5(this.seekTo,1E3,this);this.Y=g.Ia;g.H(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.RP);this.events.N(b,"captionschanged",this.eP);this.events.N(b,"captionssettingschanged",this.hJ);this.events.N(b,"videoplayerreset",this.Kw);this.events.N(b,"mdxautoplaycancel",function(){d.Ob.uF()});
a=this.Ob;a.Ga();a.subscribe("proxyStateChange",this.YH,this);a.subscribe("remotePlayerChange",this.jt,this);a.subscribe("remoteQueueChange",this.Kw,this);a.subscribe("previousNextChange",this.VH,this);a.subscribe("nowAutoplaying",this.PH,this);a.subscribe("autoplayDismissed",this.oH,this);g.H(this,this.i);g.H(this,this.u);g.H(this,this.L);g.H(this,this.V);g.H(this,this.J);this.hJ();this.Kw();this.jt()},WMa=function(a,b){if(y7(a)){a.Ob.unsubscribe("remotePlayerChange",a.jt,a);
var c=Math.round(b.volume);b=!!b.muted;var d=Q6(a.Ob);if(c!==d.volume||b!==d.muted)a.Ob.setVolume(c,b),a.V.start();a.Ob.subscribe("remotePlayerChange",a.jt,a)}},XMa=function(a){a.Sb(0);
a.i.stop();a.Hb(new g.aJ(64))},z7=function(a,b){if(y7(a)&&!a.C){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.Vb(c,b));a.Ob.TD(a.I.getVideoData(1).videoId,c);a.B=Q6(a.Ob).trackData}},A7=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Ob.playVideo(c.videoId,b,d,e,c.playerParams,c.Ca,iKa(c));a.Hb(new g.aJ(1))},YMa=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{qG:1});
c&&c.length?(a.I.setOption("captions","track",b),a.C=!1):(a.I.loadModule("captions"),a.C=!0)}else a.I.setOption("captions","track",{})},y7=function(a){return Q6(a.Ob).videoId===a.I.getVideoData(1).videoId},B7=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",oa:"Connecting to your TV on web using a code will be going away soon"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",Da:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],oa:"Learn more"},{D:"button",Da:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],oa:"OK"}]}]}]});this.i=new g.HK(this,250);this.learnMoreButton=
this.Aa("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.Aa("ytp-mdx-manual-pairing-popup-ok");g.H(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},C7=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",oa:"You're signed out"},{D:"div",K:"ytp-mdx-popup-description",oa:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",Da:["ytp-button","ytp-mdx-privacy-popup-cancel"],oa:"Cancel"},{D:"button",Da:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],oa:"Confirm"}]}]}]});this.i=new g.HK(this,250);this.cancelButton=this.Aa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Aa("ytp-mdx-privacy-popup-confirm");g.H(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},D7=function(a){g.V.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.Gma()]},{D:"div",K:"ytp-remote-display-status-text",oa:"{{statustext}}"}]}]});this.api=a;this.i=new g.HK(this,250);g.H(this,this.i);this.N(a,"presentingplayerstatechange",this.l);ZMa(this,a.rb())},ZMa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.EH("Error on $RECEIVER_NAME",c):b.lc()||g.U(b,4)?g.EH("Playing on $RECEIVER_NAME",c):g.EH("Connected to $RECEIVER_NAME",c);a.Qa("statustext",b);a.i.show()}else a.i.hide()},E7=function(a,b){g.RO.call(this,"Play on",0,a,b);
this.I=a;this.Em={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},F7=function(a){g.fM.call(this,a);
this.Di={key:Q4(),name:"This computer"};this.nh=null;this.subscriptions=[];this.CB=this.Ob=null;this.Em=[this.Di];this.Kl=this.Di;this.Xc=new g.aJ(64);this.LG=0;this.Oe=-1;this.tq=null;this.qt=this.jw=!1;this.Yk=this.Bq=null;if(!g.jD(this.player.T())&&!g.kD(this.player.T())){a=this.player;var b=g.LL(a);b&&(b=b.cm())&&(b=new E7(a,b),g.H(this,b));b=new D7(a);g.H(this,b);g.VL(a,b.element,4);this.Bq=new C7;g.H(this,this.Bq);g.VL(a,this.Bq.element,4);g.S(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.S(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.tq=new B7,g.H(this,this.tq),g.VL(a,this.tq.element,4));this.qt=!!l7();this.jw=!!g.Tu("yt-remote-manual-pairing-warning-shown")}},G7=function(a){a.Yk&&(a.player.removeEventListener("presentingplayerstatechange",a.Yk),a.Yk=null)},$Ma=function(a,b,c){a.Xc=c;
a.player.W("presentingplayerstatechange",new g.qH(c,b))},aNa=function(a,b,c){var d=!1;
1===b?d=!a.qt:2===b&&(d=!a.jw);d&&g.sH(c,8)&&(a.player.pauseVideo(),G7(a))},H7=function(a,b){if(b.key!==a.Kl.key)if(b.key===a.Di.key)r7();
else{if(a.tq&&!a.jw&&b!==a.Di&&"cast-selector-receiver"!==b.key&&g.FD(a.player.T()))bNa(a);else{var c;(c=!g.S(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.M("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.M("SESSION_INDEX")&&!g.M("LOGGED_IN")))||a.qt||!a.Bq);(c?0:g.FD(a.player.T())||g.JD(a.player.T()))&&cNa(a)}a.Kl=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.S(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))a=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.bb(l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ca,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=iKa(c))&&(a.locationInfo=c)}i7("Connecting to: "+g.Hj(b));"cast-selector-receiver"==b.key?(k7(a||null),b=a||null,
E6()?B6().setLaunchParams(b):z6("setLaunchParams called before ready.")):!a&&u7()&&h7()==b.key?K4("yt-remote-connection-change",!0):(r7(),k7(a||null),a=g7().Vg(),(b=S4(a,b.key))&&s7(b,1))}},cNa=function(a){a.player.rb().lc()?a.player.pauseVideo():(a.Yk=function(b){aNa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Yk));
a.Bq&&a.Bq.Oc();o7()||(w7=!0)},bNa=function(a){a.player.rb().lc()?a.player.pauseVideo():(a.Yk=function(b){aNa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Yk));
a.tq&&a.tq.Oc();o7()||(w7=!0)},YKa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},s5={"'":"\\'"},dNa={},rKa={RT:"atp",E3:"ska",w2:"que",C0:"mus",D3:"sus",OX:"dsp",P2:"seq",e0:"mic",OW:"dpa",hU:"cds"},Y4,U4="",LKa=GKa("loadCastFramework")||GKa("loadCastApplicationFramework"),NKa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(c5,g.F);g.k=c5.prototype;g.k.xg=function(a){this.B=arguments;this.i=!1;this.yb?this.u=g.Sa()+this.Ef:this.yb=g.Km(this.C,this.Ef)};
g.k.stop=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.G.apply(null,this.B)))};
g.k.va=function(){this.stop();c5.Fd.va.call(this)};
g.k.LL=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null);this.u?(this.yb=g.Km(this.C,this.u-g.Sa()),this.u=null):this.l?this.i=!0:(this.i=!1,this.G.apply(null,this.B))};g.v(d5,g.F);g.k=d5.prototype;g.k.xg=function(a){this.u=arguments;this.yb||this.l?this.i=!0:e5(this)};
g.k.stop=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.yb||(this.i=!1,e5(this))};
g.k.va=function(){g.F.prototype.va.call(this);this.stop()};g5.prototype.stringify=function(a){return g.A.JSON.stringify(a,void 0)};
g5.prototype.parse=function(a){return g.A.JSON.parse(a,void 0)};var i5=new g.$l;g.v(PKa,g.Gl);k5.prototype.i=null;k5.prototype.getOptions=function(){var a;(a=this.i)||(a={},RKa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var I7;g.Ta(QKa,k5);I7=new QKa;g.k=l5.prototype;g.k.Wm=null;g.k.Ri=!1;g.k.Rq=null;g.k.OC=null;g.k.Dq=null;g.k.Mq=null;g.k.Dl=null;g.k.Hm=null;g.k.Lo=null;g.k.Ge=null;g.k.fu=0;g.k.Ui=null;g.k.Ix=null;g.k.yl=null;g.k.vr=-1;g.k.TI=!0;g.k.En=!1;g.k.Fy=0;g.k.Sw=null;var WKa={},o5={};g.k=l5.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.ZR=function(a){a=a.target;var b=this.Sw;b&&3==x5(a)?b.xg():this.JJ(a)};
g.k.JJ=function(a){try{if(a==this.Ge)a:{var b=x5(this.Ge),c=this.Ge.G,d=this.Ge.getStatus();if(g.xe&&!g.be(10)||g.ze&&!g.ae("420+")){if(4>b)break a}else if(3>b||3==b&&!g.mg&&!z5(this.Ge))break a;this.En||4!=b||7==c||(8==c||0>=d?this.i.Gi(3):this.i.Gi(2));t5(this);var e=this.Ge.getStatus();this.vr=e;var f=z5(this.Ge);(this.Ri=200==e)?(4==b&&q5(this),this.G?(XKa(this,b,f),g.mg&&this.Ri&&3==b&&(this.B.Pa(this.u,"tick",this.UR),this.u.start())):p5(this,f),this.Ri&&!this.En&&(4==b?this.i.Bu(this):(this.Ri=
!1,n5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.yl=3,j5(13)):(this.yl=0,j5(14)),q5(this),r5(this))}}catch(h){this.Ge&&z5(this.Ge)}finally{}};
g.k.UR=function(){var a=x5(this.Ge),b=z5(this.Ge);this.fu<b.length&&(t5(this),XKa(this,a,b),this.Ri&&4!=a&&n5(this))};
g.k.xR=function(a){h5((0,g.C)(this.wR,this,a),0)};
g.k.wR=function(a){this.En||(t5(this),p5(this,a),n5(this))};
g.k.gI=function(a){h5((0,g.C)(this.vR,this,a),0)};
g.k.vR=function(a){this.En||(q5(this),this.Ri=a,this.i.Bu(this),this.i.Gi(4))};
g.k.cancel=function(){this.En=!0;q5(this)};
g.k.FR=function(){this.Rq=null;var a=Date.now();0<=a-this.OC?(2!=this.Mq&&this.i.Gi(3),q5(this),this.yl=2,j5(18),r5(this)):$Ka(this,this.OC-a)};
g.k.getLastError=function(){return this.yl};g.Ta(v5,g.$l);var gLa=/^https?$/i,eNa=["POST","PUT"];g.k=v5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.V+"; newUri="+a);b=b?b.toUpperCase():"GET";this.V=a;this.u="";this.G=0;this.Fa=b;this.xa=!1;this.B=!0;this.i=this.ra?SKa(this.ra):SKa(I7);this.ma=this.ra?this.ra.getOptions():I7.getOptions();this.i.onreadystatechange=(0,g.C)(this.WH,this);try{J4(y5(this,"Opening Xhr")),this.Ca=!0,this.i.open(b,String(a),!0),this.Ca=!1}catch(f){J4(y5(this,"Error opening Xhr: "+f.message));fLa(this,f);return}a=
c||"";var e=this.headers.clone();d&&nKa(d,function(f,h){e.set(h,f)});
d=g.bb(e.yh(),dLa);c=g.A.FormData&&a instanceof g.A.FormData;!g.fb(eNa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.Ma&&(this.i.responseType=this.Ma);"withCredentials"in this.i&&this.i.withCredentials!==this.Ea&&(this.i.withCredentials=this.Ea);try{iLa(this),0<this.J&&(this.Y=cLa(this.i),J4(y5(this,"Will abort after "+this.J+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.i.timeout=this.J,this.i.ontimeout=(0,g.C)(this.ND,this)):this.X=g.Km(this.ND,this.J,this)),J4(y5(this,"Sending request")),this.L=!0,this.i.send(a),this.L=!1}catch(f){J4(y5(this,"Send error: "+f.message)),fLa(this,f)}};
g.k.ND=function(){"undefined"!=typeof g.Y_&&this.i&&(this.u="Timed out after "+this.J+"ms, aborting",this.G=8,y5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(y5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.G=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),w5(this))};
g.k.va=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),w5(this,!0));v5.Fd.va.call(this)};
g.k.WH=function(){this.Ga()||(this.Ca||this.L||this.C?hLa(this):this.EQ())};
g.k.EQ=function(){hLa(this)};
g.k.isActive=function(){return!!this.i};
g.k.isComplete=function(){return 4==x5(this)};
g.k.getStatus=function(){try{return 2<x5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.isComplete())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=jLa.prototype;g.k.Gy=null;g.k.Lg=null;g.k.Tw=!1;g.k.dJ=null;g.k.bv=null;g.k.QA=null;g.k.Hy=null;g.k.eb=null;g.k.gk=-1;g.k.wr=null;g.k.Hr=null;g.k.connect=function(a){this.Hy=a;a=A5(this.i,null,this.Hy);j5(3);this.dJ=Date.now();var b=this.i.J;null!=b?(this.wr=b[0],(this.Hr=b[1])?(this.eb=1,kLa(this)):(this.eb=2,C5(this))):(H4(a,"MODE","init"),this.Lg=new l5(this,void 0,void 0,void 0),this.Lg.Wm=this.Gy,m5(this.Lg,a,!1,null,!0),this.eb=0)};
g.k.EM=function(a){if(a)this.eb=2,C5(this);else{j5(4);var b=this.i;b.qj=b.Il.gk;J5(b,9)}a&&this.Gi(2)};
g.k.Ez=function(a){return this.i.Ez(a)};
g.k.abort=function(){this.Lg&&(this.Lg.cancel(),this.Lg=null);this.gk=-1};
g.k.OD=function(){return!1};
g.k.ZH=function(a,b){this.gk=a.vr;if(0==this.eb)if(b){try{var c=this.l.parse(b)}catch(d){a=this.i;a.qj=this.gk;J5(a,2);return}this.wr=c[0];this.Hr=c[1]}else a=this.i,a.qj=this.gk,J5(a,2);else if(2==this.eb)if(this.Tw)j5(7),this.QA=Date.now();else if("11111"==b){if(j5(6),this.Tw=!0,this.bv=Date.now(),a=this.bv-this.dJ,!g.xe||g.be(10)||500>a)this.gk=200,this.Lg.cancel(),j5(12),B5(this.i,this,!0)}else j5(8),this.bv=this.QA=Date.now(),this.Tw=!1};
g.k.Bu=function(){this.gk=this.Lg.vr;if(this.Lg.Ri)0==this.eb?this.Hr?(this.eb=1,kLa(this)):(this.eb=2,C5(this)):2==this.eb&&((!g.xe||g.be(10)?!this.Tw:200>this.QA-this.bv)?(j5(11),B5(this.i,this,!1)):(j5(12),B5(this.i,this,!0)));else{0==this.eb?j5(9):2==this.eb&&j5(10);var a=this.i;this.Lg.getLastError();a.qj=this.gk;J5(a,2)}};
g.k.Jt=function(){return this.i.Jt()};
g.k.isActive=function(){return this.i.isActive()};
g.k.Gi=function(a){this.i.Gi(a)};g.k=D5.prototype;g.k.pj=null;g.k.Wr=null;g.k.yg=null;g.k.Td=null;g.k.Iy=null;g.k.ev=null;g.k.QE=null;g.k.Cu=null;g.k.Us=0;g.k.zO=0;g.k.xf=null;g.k.Ql=null;g.k.xk=null;g.k.Mn=null;g.k.Il=null;g.k.Gx=null;g.k.nq=-1;g.k.KG=-1;g.k.qj=-1;g.k.Up=0;g.k.Jp=0;g.k.Fn=8;g.Ta(mLa,g.Gl);g.Ta(nLa,g.Gl);g.k=D5.prototype;g.k.connect=function(a,b,c,d,e){j5(0);this.Iy=b;this.Wr=c||{};d&&void 0!==e&&(this.Wr.OSID=d,this.Wr.OAID=e);this.C?(h5((0,g.C)(this.hF,this,a),100),rLa(this)):this.hF(a)};
g.k.hF=function(a){this.Il=new jLa(this);this.Il.Gy=this.pj;this.Il.l=this.B;this.Il.connect(a)};
g.k.OD=function(){return 0==this.eb};
g.k.getState=function(){return this.eb};
g.k.eI=function(a){this.Ql=null;vLa(this,a)};
g.k.dI=function(){this.xk=null;this.Td=new l5(this,this.l,"rpc",this.G);this.Td.Wm=this.pj;this.Td.Fy=0;var a=this.QE.clone();F4(a,"RID","rpc");F4(a,"SID",this.l);F4(a,"CI",this.Gx?"0":"1");F4(a,"AID",this.nq);E5(this,a);if(!g.xe||g.be(10))F4(a,"TYPE","xmlhttp"),m5(this.Td,a,!0,this.Cu,!1);else{F4(a,"TYPE","html");var b=this.Td,c=!!this.Cu;b.Mq=3;b.Dl=G4(a.clone());ZKa(b,c)}};
g.k.ZH=function(a,b){if(0!=this.eb&&(this.Td==a||this.yg==a))if(this.qj=a.vr,this.yg==a&&3==this.eb)if(7<this.Fn){try{var c=this.B.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.xk){if(this.Td)if(this.Td.Dq+3E3<this.yg.Dq)G5(this),this.Td.cancel(),this.Td=null;else break a;I5(this);j5(19)}}else this.KG=a[1],0<this.KG-this.nq&&37500>a[2]&&this.Gx&&0==this.Jp&&!this.Mn&&(this.Mn=h5((0,g.C)(this.bP,this),6E3));else J5(this,11)}else b!=dNa.DW.i&&J5(this,11);else if(this.Td==
a&&G5(this),!g.oc(b))for(a=this.B.parse(b),b=0;b<a.length;b++)c=a[b],this.nq=c[0],c=c[1],2==this.eb?"c"==c[0]?(this.l=c[1],this.Cu=c[2],c=c[3],null!=c?this.Fn=c:this.Fn=6,this.eb=3,this.xf&&this.xf.dF(),this.QE=A5(this,this.Jt()?this.Cu:null,this.Iy),wLa(this)):"stop"==c[0]&&J5(this,7):3==this.eb&&("stop"==c[0]?J5(this,7):"noop"!=c[0]&&this.xf&&this.xf.cF(c),this.Jp=0)};
g.k.bP=function(){null!=this.Mn&&(this.Mn=null,this.Td.cancel(),this.Td=null,I5(this),j5(20))};
g.k.Bu=function(a){if(this.Td==a){G5(this);this.Td=null;var b=2}else if(this.yg==a)this.yg=null,b=1;else return;this.qj=a.vr;if(0!=this.eb)if(a.Ri)1==b?(b=i5,b.dispatchEvent(new mLa(b,a.Lo?a.Lo.length:0,Date.now()-a.Dq,this.Up)),F5(this),this.u.length=0):wLa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.qj)){if(d=1==b)this.yg||this.Ql||1==this.eb||2<=this.Up?d=!1:(this.Ql=h5((0,g.C)(this.eI,this,a),xLa(this,this.Up)),this.Up++,d=!0);d=!(d||2==b&&I5(this))}if(d)switch(c){case 1:J5(this,
5);break;case 4:J5(this,10);break;case 3:J5(this,6);break;case 7:J5(this,12);break;default:J5(this,2)}}};
g.k.aN=function(a){if(!g.fb(arguments,this.eb))throw Error("Unexpected channel state: "+this.eb);};
g.k.CS=function(a){a?j5(2):(j5(1),yLa(this,8))};
g.k.Ez=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new v5;a.Ea=!1;return a};
g.k.isActive=function(){return!!this.xf&&this.xf.isActive(this)};
g.k.Gi=function(a){var b=i5;b.dispatchEvent(new nLa(b,a))};
g.k.Jt=function(){return!(!g.xe||g.be(10))};
g.k=zLa.prototype;g.k.dF=function(){};
g.k.cF=function(){};
g.k.bF=function(){};
g.k.oz=function(){};
g.k.KF=function(){return{}};
g.k.isActive=function(){return!0};g.k=ALa.prototype;g.k.isEmpty=function(){return g.gb(this.i)&&g.gb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.fb(this.i,a)||g.fb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.TEa)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.l,a)};
g.k.Ag=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Ta(K5,g.F);g.k=K5.prototype;g.k.pR=function(){this.Ef=Math.min(3E5,2*this.Ef);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Ef+15E3*Math.random();g.kn(this.i,a);this.l=g.Sa()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Ef=5E3};g.Ta(L5,zLa);g.k=L5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Mf=function(a){return this.u.Mf(a)};
g.k.W=function(a,b){return this.u.W.apply(this.u,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.Di(this.u),DLa(this),g.Di(this.l),this.l=null,this.Y=function(){return""})};
g.k.Ga=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.V="";this.l.stop();this.C=a||null;this.B=b||0;a=this.ma+"/test";b=this.ma+"/bind";var d=new D5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ra),e=this.i;e&&(e.xf=null);d.xf=this;this.i=d;M5(this);if(this.i){d=g.M("ID_TOKEN");var f=this.i.pj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.pj=f}e?(3!=e.getState()&&0==tLa(e)||e.getState(),this.i.connect(a,b,this.G,e.l,e.nq)):c?this.i.connect(a,
b,this.G,c.sessionId,c.arrayId):this.i.connect(a,b,this.G)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Vb(a,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(a):N5(this)&&(M5(this),sLa(this.i,a))};
g.k.dF=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)sLa(this.i,a[b])}this.W("handlerOpened")};
g.k.bF=function(a){var b=2==a&&401==this.i.qj;4==a||b||this.l.start();this.W("handlerError",a,b)};
g.k.oz=function(a){if(!this.l.isActive())this.W("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.KF=function(){var a={v:2};this.V&&(a.gsessionid=this.V);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Vb(a,this.C);return a};
g.k.cF=function(a){"S"==a[0]?this.V=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),qLa(this.i)):this.W("handlerMessage",new BLa(a[0],a[1]))};
g.k.hx=function(a){(this.G.loungeIdToken=a)||this.l.stop();if(this.xa&&this.i){var b=this.i.pj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.pj=b}};
g.k.jS=function(){this.l.isActive();0==tLa(this.i)&&this.connect(this.C,this.B)};O5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
O5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
O5.prototype.C=function(a){a(Error("request timed out"))};var KLa=Date.now(),R5=null,U5=Array(50),T5=-1,V5=!1;g.Ta(W5,g.O);W5.prototype.Vg=function(){return this.screens};
W5.prototype.contains=function(a){return!!R4(this.screens,a)};
W5.prototype.get=function(a){return a?S4(this.screens,a):null};
W5.prototype.info=function(a){S5(this.G,a)};g.v(X5,g.O);g.k=X5.prototype;g.k.start=function(){!this.i&&isNaN(this.yb)&&this.nI()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.yb)||(g.jp(this.yb),this.yb=NaN)};
g.k.va=function(){this.stop();g.O.prototype.va.call(this)};
g.k.nI=function(){this.yb=NaN;this.i=g.op(P5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.C)(this.NL,this),onError:(0,g.C)(this.ML,this),onTimeout:(0,g.C)(this.OL,this)})};
g.k.NL=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.B;a.name=this.G;b=-1;this.C&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.W("pairingComplete",new M4(a),b)};
g.k.ML=function(a){this.i=null;a.status&&404==a.status?this.l>=fNa.length?this.W("pairingFailed",Error("DIAL polling timed out")):(a=fNa[this.l],this.yb=g.hp((0,g.C)(this.nI,this),a),this.l++):this.W("pairingFailed",Error("Server error "+a.status))};
g.k.OL=function(){this.i=null;this.W("pairingFailed",Error("Server not responding"))};
var fNa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(Z5,W5);g.k=Z5.prototype;g.k.start=function(){Y5(this)&&this.W("screenChange");!g.Tu("yt-remote-lounge-token-expiration")&&OLa(this);g.jp(this.i);this.i=g.hp((0,g.C)(this.start,this),1E4)};
g.k.add=function(a,b){Y5(this);LLa(this,a);$5(this,!1);this.W("screenChange");b(a);a.token||OLa(this)};
g.k.remove=function(a,b){var c=Y5(this);NLa(this,a)&&($5(this,!1),c=!0);b(a);c&&this.W("screenChange")};
g.k.Ex=function(a,b,c,d){var e=Y5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,$5(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.W("screenChange")};
g.k.va=function(){g.jp(this.i);Z5.Fd.va.call(this)};
g.k.xN=function(a){Y5(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}$5(this,!b);b&&S5(this.G,"Missed "+b+" lounge tokens.")};
g.k.wN=function(a){S5(this.G,"Requesting lounge tokens failed: "+a)};g.v(b6,g.O);g.k=b6.prototype;g.k.start=function(){var a=parseInt(g.Tu("yt-remote-fast-check-period")||"0",10);(this.B=g.Sa()-144E5<a?0:a)?e6(this):(this.B=g.Sa()+3E5,g.Su("yt-remote-fast-check-period",this.B),this.NB())};
g.k.isEmpty=function(){return g.Ob(this.i)};
g.k.update=function(){a6("Updating availability on schedule.");var a=this.G(),b=g.Cb(this.i,function(c,d){return c&&!!S4(a,d)},this);
d6(this,b)};
g.k.va=function(){g.jp(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.O.prototype.va.call(this)};
g.k.NB=function(){g.jp(this.u);this.u=NaN;this.l&&this.l.abort();var a=QLa(this);if(I4(a)){var b=P5(this.C,"/pairing/get_screen_availability");this.l=Q5(this.C,b,{lounge_token:g.Jb(a).join(",")},(0,g.C)(this.YQ,this,a),(0,g.C)(this.XQ,this))}else d6(this,{}),e6(this)};
g.k.YQ=function(a,b){this.l=null;var c=g.Jb(QLa(this));if(g.xb(c,g.Jb(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;d6(this,c);e6(this)}else this.Gd("Changing Screen set during request."),this.NB()};
g.k.XQ=function(a){this.Gd("Screen availability failed: "+a);this.l=null;e6(this)};
g.k.Gd=function(a){S5("OnlineScreenService",a)};g.Ta(f6,W5);g.k=f6.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.W("screenChange"),this.i.isEmpty()||this.W("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Ex=function(a,b,c,d){this.l.contains(a)?this.l.Ex(a,b,c,d):(a="Updating name of unknown screen: "+a.name,S5(this.G,a),d(Error(a)))};
g.k.Vg=function(a){return a?this.screens:g.nb(this.screens,g.Je(this.u,function(b){return!this.contains(b)},this))};
g.k.PD=function(){return g.Je(this.Vg(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.QD=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new X5(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.Di(l);e(g6(h,m),n)});
l.subscribe("pairingFailed",function(m){g.Di(l);f(m)});
l.start();return(0,g.C)(l.stop,l)};
g.k.PL=function(a,b,c,d){g.op(P5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.C)(function(e,f){e=new M4(f.screen||{});if(!e.name||ULa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);ULa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(g6(this,e))},this),
onError:(0,g.C)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.C)(function(){d(Error("pairing request timed out."))},this)})};
g.k.va=function(){g.Di(this.l);g.Di(this.i);f6.Fd.va.call(this)};
g.k.DN=function(){WLa(this);this.W("screenChange");this.i.update()};
f6.prototype.dispose=f6.prototype.dispose;g.Ta(i6,g.O);g.k=i6.prototype;g.k.getScreen=function(){return this.B};
g.k.Zf=function(a){this.Ga()||(a&&k6(this,""+a),this.B=null,this.W("sessionScreen",null))};
g.k.info=function(a){S5(this.xa,a)};
g.k.RD=function(){return null};
g.k.XB=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.C)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.C)(function(){k6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.va=function(){this.XB("");i6.Fd.va.call(this)};g.v(l6,i6);g.k=l6.prototype;g.k.WB=function(a){if(this.l){if(this.l==a)return;k6(this,"Overriding cast session with new session object");eMa(this);this.ma=!1;this.V="unknown";this.l.removeUpdateListener(this.Y);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra)}this.l=a;this.l.addUpdateListener(this.Y);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra);aMa(this,"getMdxSessionStatus")};
g.k.oq=function(a){this.info("launchWithParams no-op for Cast: "+g.Hj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.C)(function(){this.Zf()},this),(0,g.C)(function(){this.Zf(Error("Failed to stop receiver app."))},this)):this.Zf(Error("Stopping cast device without session."))};
g.k.XB=function(){};
g.k.va=function(){this.info("disposeInternal");eMa(this);this.l&&(this.l.removeUpdateListener(this.Y),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra));this.l=null;i6.prototype.va.call(this)};
g.k.JR=function(a,b){if(!this.Ga())if(b)if(b=f5(b),g.Ma(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Hj(b)),a){case "mdxSessionStatus":ZLa(this,b);break;case "loungeToken":bMa(this,b);break;default:k6(this,"Unknown youtube message: "+a)}else k6(this,"Unable to parse message.");else k6(this,"No data in message.")};
g.k.ZF=function(a,b,c,d){g.jp(this.L);this.L=0;TLa(this.u,this.i.label,a,this.i.friendlyName,(0,g.C)(function(e){e?b(e):0<=d?(k6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.hp((0,g.C)(this.ZF,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.RD=function(){return this.l};
g.k.QL=function(a){this.Ga()||a||(k6(this,"Cast session died."),this.Zf())};g.v(o6,i6);g.k=o6.prototype;g.k.WB=function(a){this.l=a;this.l.addUpdateListener(this.Ca)};
g.k.oq=function(a){this.Ba=a;this.X()};
g.k.stop=function(){lMa(this);this.l?this.l.stop((0,g.C)(this.Zf,this,null),(0,g.C)(this.Zf,this,"Failed to stop DIAL device.")):this.Zf()};
g.k.va=function(){lMa(this);this.l&&this.l.removeUpdateListener(this.Ca);this.l=null;i6.prototype.va.call(this)};
g.k.RL=function(a){this.Ga()||a||(k6(this,"DIAL session died."),this.C(),this.C=g.Ia,this.Zf())};g.v(s6,i6);s6.prototype.stop=function(){this.Zf()};
s6.prototype.WB=function(){};
s6.prototype.oq=function(){g.jp(this.l);this.l=NaN;var a=S4(this.u.Vg(),this.i.label);a?j6(this,a):this.Zf(Error("No such screen"))};
s6.prototype.va=function(){g.jp(this.l);this.l=NaN;i6.prototype.va.call(this)};g.v(t6,g.O);g.k=t6.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.L);this.V||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.C)(this.IQ,this);c=new chrome.cast.ApiConfig(c,(0,g.C)(this.aI,this),e,d,a);c.customDialLaunchCallback=(0,g.C)(this.vP,this);chrome.cast.initialize(c,(0,g.C)(function(){this.Ga()||
(chrome.cast.addReceiverActionListener(this.G),HLa(),this.l.subscribe("onlineScreenChange",(0,g.C)(this.SD,this)),this.u=nMa(this),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(f){this.Gd("Failed to set initial custom receivers: "+g.Hj(f))},this)),this.W("yt-remote-cast2-availability-change",v6(this)),b(!0))},this),(0,g.C)(function(f){this.Gd("Failed to initialize API: "+g.Hj(f));
b(!1)},this))};
g.k.oS=function(a,b){u6("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)u6("Unsetting old screen status: "+this.i.i.friendlyName),w6(this,null)}if(a&&b){if(!this.i){c=S4(this.l.Vg(),a);if(!c){u6("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){u6("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=mMa(this,c);a||(u6("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(a),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(d){this.Gd("Failed to set initial custom receivers: "+g.Hj(d))},this)));
u6("setConnectedScreenStatus: new active receiver: "+a.friendlyName);w6(this,new s6(this.l,a),!0)}this.i.XB(b)}else u6("setConnectedScreenStatus: no screen.")};
g.k.pS=function(a){this.Ga()?this.Gd("Setting connection data on disposed cast v2"):this.i?this.i.oq(a):this.Gd("Setting connection data without a session")};
g.k.TL=function(){this.Ga()?this.Gd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),w6(this,null)):u6("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.C)(this.aI,this),(0,g.C)(this.bR,this))};
g.k.va=function(){this.l.unsubscribe("onlineScreenChange",(0,g.C)(this.SD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.G);var a=ELa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.Di(this.i);g.O.prototype.va.call(this)};
g.k.Gd=function(a){S5("Controller",a)};
g.k.cI=function(a,b){this.i==a&&(b||w6(this,null),this.W("yt-remote-cast2-session-change",b))};
g.k.FQ=function(a,b){if(!this.Ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),u6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)u6("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{u6("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.W("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:w6(this,
new s6(this.l,a));break;case chrome.cast.ReceiverType.DIAL:w6(this,new o6(this.l,a,this.C,this.B));break;case chrome.cast.ReceiverType.CAST:w6(this,new l6(this.l,a,this.B));break;default:this.Gd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Gd("Stopping receiver w/o session: "+a.friendlyName)}else this.Gd("onReceiverAction_ called without receiver.")};
g.k.vP=function(a){if(this.Ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Gd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Gd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return u6("Reselecting dial screen."),
this.W("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Gd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);w6(this,new o6(this.l,b,this.C,this.B))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,p6(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=iMa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.No(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=jMa(b,c)):a=jMa(b,c)):a=r6(b);return a};
g.k.aI=function(a){if(!this.Ga()){u6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)u6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),w6(this,new l6(this.l,b,this.B),!0);else{this.Gd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=S4(this.l.Vg(),c.label);d&&N4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(u6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Di(this.i),this.i=new l6(this.l,b,this.B),this.i.subscribe("sessionScreen",(0,g.C)(this.cI,this,this.i)),this.i.oq(null));this.i.WB(a)}}};
g.k.SL=function(){return this.i?this.i.RD():null};
g.k.bR=function(a){this.Ga()||(this.Gd("Failed to estabilish a session: "+g.Hj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&w6(this,null))};
g.k.IQ=function(a){u6("Receiver availability updated: "+a);if(!this.Ga()){var b=v6(this);this.J=a==chrome.cast.ReceiverAvailability.AVAILABLE;v6(this)!=b&&this.W("yt-remote-cast2-availability-change",v6(this))}};
g.k.SD=function(){this.Ga()||(this.u=nMa(this),u6("Updating custom receivers: "+g.Hj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(){this.Gd("Failed to set custom receivers.")},this)),this.W("yt-remote-cast2-availability-change",v6(this)))};
t6.prototype.setLaunchParams=t6.prototype.pS;t6.prototype.setConnectedScreenStatus=t6.prototype.oS;t6.prototype.stopSession=t6.prototype.TL;t6.prototype.getCastSession=t6.prototype.SL;t6.prototype.requestSession=t6.prototype.requestSession;t6.prototype.init=t6.prototype.init;t6.prototype.dispose=t6.prototype.dispose;var C6=[];g.k=H6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";I6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Fj=a.hasPrevious,this.hasNext=a.hasNext,this.J=a.playerTime,this.G=a.playerTimeAt,this.B=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.L=a.loadedTime,this.u=a.liveIngestionTime,this.l=
!isNaN(this.u))};
g.k.lc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.l?this.C+J6(this):this.C};
g.k.clone=function(){return new H6(N6(this))};g.v(P6,g.O);g.k=P6.prototype;g.k.getState=function(){return this.eb};
g.k.play=function(){R6(this)?(this.i?this.i.play(null,g.Ia,W6(this,"play")):V6(this,"play"),U6(this,1,L6(Q6(this))),this.W("remotePlayerChange")):S6(this,this.play)};
g.k.pause=function(){R6(this)?(this.i?this.i.pause(null,g.Ia,W6(this,"pause")):V6(this,"pause"),U6(this,2,L6(Q6(this))),this.W("remotePlayerChange")):S6(this,this.pause)};
g.k.seekTo=function(a){if(R6(this)){if(this.i){var b=Q6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.lc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,W6(this,"seekTo",{newTime:a}))}else V6(this,"seekTo",{newTime:a});U6(this,3,a);this.W("remotePlayerChange")}else S6(this,g.Pa(this.seekTo,a))};
g.k.stop=function(){if(R6(this)){this.i?this.i.stop(null,g.Ia,W6(this,"stopVideo")):V6(this,"stopVideo");var a=Q6(this);a.index=-1;a.videoId="";I6(a);T6(this,a);this.W("remotePlayerChange")}else S6(this,this.stop)};
g.k.setVolume=function(a,b){if(R6(this)){var c=Q6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.C)(function(){S5("CP","set receiver volume: "+d)},this),(0,g.C)(function(){this.Gd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.C)(function(){S5("CP","set receiver muted: "+b)},this),(0,g.C)(function(){this.Gd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);V6(this,"setVolume",e)}c.muted=b;c.volume=a;T6(this,c)}else S6(this,g.Pa(this.setVolume,a,b))};
g.k.TD=function(a,b){if(R6(this)){var c=Q6(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Hj(b.style),g.Vb(a,c.trackData));V6(this,"setSubtitlesTrack",a);T6(this,c)}else S6(this,g.Pa(this.TD,a,b))};
g.k.setAudioTrack=function(a,b){R6(this)?(b=b.getLanguageInfo().getId(),V6(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=Q6(this),a.audioTrackId=b,T6(this,a)):S6(this,g.Pa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=Q6(this);c=c||0;var m={videoId:a,currentIndex:c};M6(l,a,c);void 0!==b&&(K6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Hj(h));V6(this,"setPlaylist",m);d||T6(this,l)};
g.k.Ow=function(a,b){if(R6(this)){if(a&&b){var c=Q6(this);M6(c,a,b);T6(this,c)}V6(this,"previous")}else S6(this,g.Pa(this.Ow,a,b))};
g.k.nextVideo=function(a,b){if(R6(this)){if(a&&b){var c=Q6(this);M6(c,a,b);T6(this,c)}V6(this,"next")}else S6(this,g.Pa(this.nextVideo,a,b))};
g.k.uF=function(){R6(this)?V6(this,"dismissAutoplay"):S6(this,this.uF)};
g.k.dispose=function(){if(3!=this.eb){var a=this.eb;this.eb=3;this.W("proxyStateChange",a,this.eb)}g.O.prototype.dispose.call(this)};
g.k.va=function(){zMa(this);this.u=null;this.B.clear();O6(this,null);g.O.prototype.va.call(this)};
g.k.ZB=function(a){if((a!=this.eb||2==a)&&3!=this.eb&&0!=a){var b=this.eb;this.eb=a;this.W("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.gb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.CQ=function(a,b){this.W(a,b)};
g.k.hP=function(a){if(!a)this.Xs(null),O6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=Q6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)S5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,T6(this,b)}};
g.k.Xs=function(a){S5("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),AMa(this),this.W("remotePlayerChange")};
g.k.gP=function(a){a?(AMa(this),this.W("remotePlayerChange")):this.Xs(null)};
g.k.sC=function(){V6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.oP=function(){var a=wMa();a&&O6(this,a)};
g.k.Gd=function(a){S5("CP",a)};g.v(X6,g.O);g.k=X6.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime;b=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);b&&(l.locationInfo=b);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Zb.listId=c);this.Zb.videoId=d;this.Zb.index=h||0;this.Zb.state=3;K6(this.Zb,m);this.B="UNSUPPORTED";Y6("Connecting with setPlaylist and params: "+g.Hj(l));this.i.connect({method:"setPlaylist",
params:g.Hj(l)},a,zKa())}else Y6("Connecting without params"),this.i.connect({},a,zKa());CMa(this)};
g.k.hx=function(a){this.i.hx(a)};
g.k.dispose=function(){this.Ga()||(this.W("beforeDispose"),Z6(this,3));g.O.prototype.dispose.call(this)};
g.k.va=function(){$6(this);b7(this);a7(this);g.jp(this.J);this.J=NaN;g.jp(this.L);this.L=NaN;this.u=null;g.Op(this.V);this.V.length=0;this.i.dispose();g.O.prototype.va.call(this);this.B=this.G=this.l=this.Zb=this.i=null};
g.k.tN=function(){this.Qp(2)};
g.k.lP=function(){Y6("Channel opened");this.ma&&(this.ma=!1,a7(this),this.Y=g.hp((0,g.C)(function(){Y6("Timing out waiting for a screen.");this.Qp(1)},this),15E3));
DKa(CLa(this.i),this.Ca)};
g.k.iP=function(){Y6("Channel closed");isNaN(this.C)?X4(!0):X4();this.dispose()};
g.k.jP=function(a,b){X4();isNaN(this.zs())?(b&&"shortLived"==this.ra&&this.W("browserChannelAuthError",a),Y6("Channel error: "+a+" without reconnection"),this.dispose()):(this.ma=!0,Y6("Channel error: "+a+" with reconnection in "+this.zs()+" ms"),Z6(this,2))};
g.k.kP=function(a){a.params?Y6("Received: action="+a.action+", params="+g.Hj(a.params)):Y6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=f5(a.params.devices);this.l=g.Oc(a,function(c){return new L4(c)});
a=!!g.bb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
FMa(this,a);break;case "loungeScreenDisconnected":g.lb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
FMa(this,!1);break;case "remoteConnected":var b=new L4(f5(a.params.device));g.bb(this.l,function(c){return b?c.id==b.id:!1})||jKa(this.l,b);
break;case "remoteDisconnected":b=new L4(f5(a.params.device));g.lb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":HMa(this,a);break;case "nowPlaying":JMa(this,a);break;case "onStateChange":IMa(this,a);break;case "onAdStateChange":KMa(this,a);break;case "onVolumeChanged":LMa(this,a);break;case "onSubtitlesTrackChanged":GMa(this,a);break;case "nowAutoplaying":MMa(this,a);break;case "autoplayDismissed":this.W("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.W("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.W("autoplayModeChange",this.B);"DISABLED"==this.B&&this.W("autoplayDismissed");break;case "onHasPreviousNextChanged":NMa(this,a);break;case "requestAssistedSignIn":this.W("assistedSignInRequested",a.params.authCode);break;default:Y6("Unrecognized action: "+a.action)}};
g.k.fS=function(){if(this.u){var a=this.u;this.u=null;this.Zb.videoId!=a&&c7(this,"getNowPlaying")}};
g.k.oN=function(){var a=3;this.Ga()||(a=0,isNaN(this.zs())?N5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Qp=function(a){Y6("Disconnecting with "+a);$6(this);this.W("beforeDisconnect",a);1==a&&X4();DLa(this.i,a);this.dispose()};
g.k.mN=function(){var a=this.Zb;this.u&&(a=this.Zb.clone(),M6(a,this.u,a.index));return N6(a)};
g.k.qS=function(a){var b=new H6(a);b.videoId&&b.videoId!=this.Zb.videoId&&(this.u=b.videoId,g.jp(this.J),this.J=g.hp((0,g.C)(this.fS,this),5E3));var c=[];this.Zb.listId==b.listId&&this.Zb.videoId==b.videoId&&this.Zb.index==b.index||c.push("remoteQueueChange");this.Zb.playerState==b.playerState&&this.Zb.volume==b.volume&&this.Zb.muted==b.muted&&L6(this.Zb)==L6(b)&&g.Hj(this.Zb.trackData)==g.Hj(b.trackData)||c.push("remotePlayerChange");this.Zb.reset(a);g.zb(c,function(d){this.W(d)},this)};
g.k.YF=function(){var a=this.i.G.id,b=g.bb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.zs=function(){var a=this.i;return a.l.isActive()?a.l.l-g.Sa():NaN};
g.k.kN=function(){return this.B||"UNSUPPORTED"};
g.k.lN=function(){return this.G||""};
g.k.UL=function(){if(!isNaN(this.zs())){var a=this.i.l;a.i.xg();a.start()}};
g.k.nS=function(a,b){c7(this,a,b);EMa(this)};
g.k.UD=function(){var a=g.yo("SID","")||"",b=g.yo("SAPISID","")||"",c=g.yo("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.tf(g.Xe(a),2);b=g.tf(g.Xe(b),2);c=g.tf(g.Xe(c),2);return g.tf(g.Xe(a+","+b+","+c),2)};
X6.prototype.subscribe=X6.prototype.subscribe;X6.prototype.unsubscribeByKey=X6.prototype.Mf;X6.prototype.getProxyState=X6.prototype.oN;X6.prototype.disconnect=X6.prototype.Qp;X6.prototype.getPlayerContextData=X6.prototype.mN;X6.prototype.setPlayerContextData=X6.prototype.qS;X6.prototype.getOtherConnectedRemoteId=X6.prototype.YF;X6.prototype.getReconnectTimeout=X6.prototype.zs;X6.prototype.getAutoplayMode=X6.prototype.kN;X6.prototype.getAutoplayVideoId=X6.prototype.lN;X6.prototype.reconnect=X6.prototype.UL;
X6.prototype.sendMessage=X6.prototype.nS;X6.prototype.getXsrfToken=X6.prototype.UD;g.v(d7,W5);g.k=d7.prototype;g.k.Vg=function(a){return this.Df.$_gs(a)};
g.k.contains=function(a){return!!this.Df.$_c(a)};
g.k.get=function(a){return this.Df.$_g(a)};
g.k.start=function(){this.Df.$_st()};
g.k.add=function(a,b,c){this.Df.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Df.$_r(a,b,c)};
g.k.Ex=function(a,b,c,d){this.Df.$_un(a,b,c,d)};
g.k.va=function(){for(var a=0,b=this.i.length;a<b;++a)this.Df.$_ubk(this.i[a]);this.i.length=0;this.Df=null;W5.prototype.va.call(this)};
g.k.VL=function(){this.W("screenChange")};
g.k.jQ=function(){this.W("onlineScreenChange")};
f6.prototype.$_st=f6.prototype.start;f6.prototype.$_gspc=f6.prototype.PL;f6.prototype.$_gsppc=f6.prototype.QD;f6.prototype.$_c=f6.prototype.contains;f6.prototype.$_g=f6.prototype.get;f6.prototype.$_a=f6.prototype.add;f6.prototype.$_un=f6.prototype.Ex;f6.prototype.$_r=f6.prototype.remove;f6.prototype.$_gs=f6.prototype.Vg;f6.prototype.$_gos=f6.prototype.PD;f6.prototype.$_s=f6.prototype.subscribe;f6.prototype.$_ubk=f6.prototype.Mf;var q7=null,w7=!1,e7=null,f7=null,v7=null,j7=[];g.v(x7,g.F);g.k=x7.prototype;g.k.va=function(){g.F.prototype.va.call(this);this.i.stop();this.u.stop();this.L.stop();this.Y();var a=this.Ob;a.unsubscribe("proxyStateChange",this.YH,this);a.unsubscribe("remotePlayerChange",this.jt,this);a.unsubscribe("remoteQueueChange",this.Kw,this);a.unsubscribe("previousNextChange",this.VH,this);a.unsubscribe("nowAutoplaying",this.PH,this);a.unsubscribe("autoplayDismissed",this.oH,this);this.Ob=this.l=null};
g.k.VD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Ob.eb)if(y7(this)){if(!Q6(this.Ob).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":Q6(this.Ob).lc()?this.Ob.pause():this.Ob.play();break;case "control_play":this.Ob.play();break;case "control_pause":this.Ob.pause();break;case "control_seek":this.J.xg(c[0],c[1]);break;case "control_subtitles_set_track":z7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.I.getCurrentTime();A7(this,0===c?void 0:c);break;case "control_seek":A7(this,c[0]);break;case "control_subtitles_set_track":z7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.eP=function(a){this.L.xg(a)};
g.k.US=function(a){this.VD("control_subtitles_set_track",g.Ob(a)?null:a)};
g.k.hJ=function(){var a=this.I.getOption("captions","track");g.Ob(a)||z7(this,a)};
g.k.Sb=function(a){this.l.Sb(a,this.I.getVideoData().lengthSeconds)};
g.k.RP=function(){g.Ob(this.B)||YMa(this,this.B);this.C=!1};
g.k.YH=function(a,b){this.u.stop();2===b&&this.cJ()};
g.k.jt=function(){if(y7(this)){this.i.stop();var a=Q6(this.Ob);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Oe=1;break;case 1082:case 1083:this.l.Oe=0;break;default:this.l.Oe=-1}switch(a.playerState){case 1081:case 1:this.Hb(new g.aJ(8));this.bJ();break;case 1085:case 3:this.Hb(new g.aJ(9));break;case 1083:case 0:this.Hb(new g.aJ(2));this.J.stop();this.Sb(this.I.getVideoData().lengthSeconds);break;case 1084:this.Hb(new g.aJ(4));break;case 2:this.Hb(new g.aJ(4));this.Sb(L6(a));
break;case -1:this.Hb(new g.aJ(64));break;case -1E3:this.Hb(new g.aJ(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=Q6(this.Ob).trackData;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,YMa(this,a));a=Q6(this.Ob);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===a.muted||this.V.isActive()||this.CJ()}else XMa(this)};
g.k.VH=function(){this.I.W("mdxpreviousnextchange")};
g.k.Kw=function(){y7(this)||XMa(this)};
g.k.PH=function(a){isNaN(a)||this.I.W("mdxnowautoplaying",a)};
g.k.oH=function(){this.I.W("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){y7(this)&&this.Ob.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===Q6(this.Ob).playerState?A7(this,a):b&&this.Ob.seekTo(a)};
g.k.CJ=function(){var a=this;if(y7(this)){var b=Q6(this.Ob);this.events.ac(this.X);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.X=this.events.N(this.I,"onVolumeChange",function(c){WMa(a,c)})}};
g.k.bJ=function(){this.i.stop();if(!this.Ob.Ga()){var a=Q6(this.Ob);a.lc()&&this.Hb(new g.aJ(8));this.Sb(L6(a));this.i.start()}};
g.k.cJ=function(){this.u.stop();this.i.stop();var a=this.Ob.u.getReconnectTimeout();2==this.Ob.eb&&!isNaN(a)&&this.u.start()};
g.k.Hb=function(a){this.u.stop();var b=this.G;if(!g.fJ(b,a)){var c=g.U(a,2);c!==g.U(this.G,2)&&this.I.Po(c);this.G=a;$Ma(this.l,b,a)}};g.v(B7,g.V);B7.prototype.Oc=function(){this.i.show()};
B7.prototype.Ab=function(){this.i.hide()};
B7.prototype.l=function(){g.HI("https://support.google.com/youtube/answer/7640706")};
B7.prototype.u=function(){K4("mdx-manual-pairing-popup-ok");this.Ab()};g.v(C7,g.V);C7.prototype.Oc=function(){this.i.show()};
C7.prototype.Ab=function(){this.i.hide()};
C7.prototype.l=function(){K4("mdx-privacy-popup-cancel");this.Ab()};
C7.prototype.u=function(){K4("mdx-privacy-popup-confirm");this.Ab()};g.v(D7,g.V);D7.prototype.l=function(a){ZMa(this,a.state)};g.v(E7,g.RO);E7.prototype.C=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.Em=g.Ab(a,this.i,this),g.SO(this,g.Oc(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.jh(a),this.enable(!0)):this.enable(!1)};
E7.prototype.i=function(a){return a.key};
E7.prototype.gi=function(a){return"cast-selector-receiver"===a?"Cast...":this.Em[a].name};
E7.prototype.Xe=function(a){g.RO.prototype.Xe.call(this,a);this.I.setOption("remote","currentReceiver",this.Em[a]);this.vb.Ab()};g.v(F7,g.fM);g.k=F7.prototype;
g.k.create=function(){var a=this.player.T(),b=g.hD(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.S(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.S(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.S(a.experiments,"enable_cast_short_lived_lounge_token")};RMa(b,a);this.subscriptions.push(g.Mq("yt-remote-before-disconnect",this.dP,this));this.subscriptions.push(g.Mq("yt-remote-connection-change",this.JQ,this));this.subscriptions.push(g.Mq("yt-remote-receiver-availability-change",
this.XH,this));this.subscriptions.push(g.Mq("yt-remote-auto-connect",this.HQ,this));this.subscriptions.push(g.Mq("yt-remote-receiver-resumed",this.GQ,this));this.subscriptions.push(g.Mq("mdx-privacy-popup-confirm",this.XR,this));this.subscriptions.push(g.Mq("mdx-privacy-popup-cancel",this.WR,this));this.subscriptions.push(g.Mq("mdx-manual-pairing-popup-ok",this.nO,this));this.XH()};
g.k.load=function(){this.player.cancelPlayback();g.fM.prototype.load.call(this);this.nh=new x7(this,this.player,this.Ob);var a=(a=VMa())?a.currentTime:0;var b=u7()?new P6(o7(),void 0):null;0==a&&b&&(a=L6(Q6(b)));0!==a&&this.Sb(a);$Ma(this,this.Xc,this.Xc);this.player.Vj(6)};
g.k.unload=function(){this.player.W("mdxautoplaycanceled");this.Kl=this.Di;g.Ei(this.nh,this.Ob);this.Ob=this.nh=null;g.fM.prototype.unload.call(this);this.player.Vj(5);G7(this)};
g.k.va=function(){g.Nq(this.subscriptions);g.fM.prototype.va.call(this)};
g.k.Qj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.nh.VD.apply(this.nh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.Oe};
g.k.pN=function(){return this.loaded?this.nh.suggestion:null};
g.k.Fj=function(){return this.Ob?Q6(this.Ob).Fj:!1};
g.k.hasNext=function(){return this.Ob?Q6(this.Ob).hasNext:!1};
g.k.Sb=function(a,b){this.LG=a||0;this.player.W("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.LG};
g.k.getProgressState=function(){var a=Q6(this.Ob),b=this.player.getVideoData();return{allowSeeking:g.S(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Ne():!a.isAdPlaying()&&this.player.Ne(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.l?a.u+J6(a):a.u,isAtLiveHead:1>=(a.l?a.i+J6(a):a.i)-this.getCurrentTime(),loaded:a.L,seekableEnd:a.l?a.i+J6(a):a.i,seekableStart:0<a.B?a.B+
J6(a):a.B}};
g.k.nextVideo=function(){this.Ob&&this.Ob.nextVideo()};
g.k.Ow=function(){this.Ob&&this.Ob.Ow()};
g.k.dP=function(a){1===a&&(this.CB=this.Ob?Q6(this.Ob):null)};
g.k.JQ=function(){var a=u7()?new P6(o7(),void 0):null;if(a){var b=this.Kl;this.loaded&&this.unload();this.Ob=a;this.CB=null;b.key!==this.Di.key&&(this.Kl=b,this.load())}else g.Di(this.Ob),this.Ob=null,this.loaded&&(this.unload(),(a=this.CB)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,L6(a)));this.player.W("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.XH=function(){var a=[this.Di],b=a.concat,c=SMa();D6()&&g.Tu("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Em=b.call(a,c);a=p7()||this.Di;H7(this,a);this.player.La("onMdxReceiversChange")};
g.k.HQ=function(){var a=p7();H7(this,a)};
g.k.GQ=function(){this.Kl=p7()};
g.k.XR=function(){this.qt=!0;G7(this);w7=!1;q7&&s7(q7,1);q7=null};
g.k.WR=function(){this.qt=!1;G7(this);H7(this,this.Di);this.Kl=this.Di;w7=!1;q7=null;this.player.playVideo()};
g.k.nO=function(){this.jw=!0;G7(this);g.Su("yt-remote-manual-pairing-warning-shown",!0,2592E3);w7=!1;q7&&s7(q7,1);q7=null};
g.k.Ie=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Em;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?F6():H7(this,b)),this.loaded?this.Kl:this.Di;case "quickCast":return 2===this.Em.length&&"cast-selector-receiver"===this.Em[1].key?(b&&F6(),!0):!1}};
g.k.sC=function(){this.Ob.sC()};
g.k.Th=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.lM.remote=F7;})(_yt_player);
